version: '3'
services:
  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'database:db'
    ports:
      - '9090:80'
    env_file:
      - 'database.env'
  
  # MySQL 5.7 Database
  database:
    image: mysql:5.7
    restart: always
    ports:
      - '3300:3300'
    expose:
      - '3308'
    volumes:
      - mysqldb:/var/lib/mysql
    env_file:
      - 'database.env'

  # NginX Server
  nginx:
    image: nginx:latest
    ports:
      - '8082:8082'
      - '8000:8082'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


  # Authentication
  authentication: 
    build: './authentication'
    ports:
      - '9000:3000'
    links:
      - 'database:database'
    volumes:
      - ./authentication:/src
    env_file:
      - 'database.env'

  # token
  token: 
    build: './token'
    ports:
      - '9002:3000'
    links:
      - 'database:database'
    volumes:
      - ./token:/src
    env_file:
      - 'database.env'


  # SMS
  sms: 
    build: './sms'
    ports:
      - '9006:3000'
    links:
      - 'database:database'
    volumes:
      - ./sms:/src
    env_file:
      - 'database.env'

  #events
  events : 
    build: './events'
    ports:
      - '9008:3000'
    links:
      - 'database:database'
    volumes:
      - ./events:/src
    env_file:
      - 'database.env'


  # roles
  roles: 
    build: './roles'
    ports:
      - '9004:3000'
    links:
      - 'database:database'
    volumes:
      - ./roles:/src
    env_file:
      - 'database.env'

  # college
  college: 
    build: './college'
    ports:
      - '9010:3000'
    links:
      - 'database:database'
    volumes:
      - ./college:/src
    env_file:
      - 'database.env'
      

volumes:
  mysqldb:
